# Generated by Django 5.2.7 on 2025-10-15 06:12

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='passwd',
        ),
        migrations.AddField(
            model_name='user',
            name='Experience',
            field=models.CharField(choices=[('1Y', '1 Years'), ('2Y', '2 Years'), ('3Y', '3 Years'), ('4Y', '4 Years'), ('5Y', '5 Years'), ('6Y', '6 Years'), ('7Y+', '7 Years')], default='1Y', verbose_name='Experience'),
        ),
        migrations.AddField(
            model_name='user',
            name='technology',
            field=models.CharField(blank=True, choices=[('BD', 'backend'), ('FD', 'frontend'), ('FS', 'fullstack')], verbose_name='Technology'),
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone', models.CharField(max_length=25, unique=True)),
                ('Bio', models.FileField(default='PENDING', upload_to='Profile/BioFile')),
                ('Project', models.CharField(max_length=90)),
                ('Project_AssignedDate', models.DateTimeField()),
                ('Assigner', models.CharField(choices=[('MG', 'Manager'), ('EP', 'Employee'), ('OWN', 'Owner'), ('HR', 'HR')], max_length=60)),
                ('TeamMembers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None)),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None)),
                ('PreviousCompany', models.FileField(default='Null', upload_to='Profile/PreCom/')),
                ('DayUpdate', models.CharField(default='PENDING', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HrProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('FullName', models.CharField(max_length=250)),
                ('department', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15, unique=True)),
                ('candidates_managed', models.PositiveIntegerField(default=0)),
                ('employees_under', models.PositiveIntegerField(default=0)),
                ('interviews_scheduled', models.PositiveIntegerField(default=0)),
                ('can_hire', models.BooleanField(default=True)),
                ('max_open_positions', models.IntegerField(default=1)),
                ('current_openings', models.IntegerField(default=0)),
                ('can_assign_to_manager', models.BooleanField(default=True)),
                ('can_approve_leave', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hr_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InternProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('FullName', models.CharField(max_length=250)),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None)),
                ('Task', models.CharField(max_length=200, null=True)),
                ('Assigner', models.CharField(choices=[('MG', 'Manager'), ('EP', 'Employee'), ('OWN', 'Owner'), ('HR', 'HR')], max_length=60)),
                ('next_Intrest', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None)),
                ('Part_of_Project', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intern_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManagerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('FullName', models.CharField(max_length=250)),
                ('department', models.CharField(max_length=100)),
                ('Team', models.CharField(default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NewJoineProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('FullName', models.CharField(max_length=250)),
                ('Resume', models.FileField(upload_to='Profile/Resumes/')),
                ('AdharCard', models.ImageField(upload_to='Profile/AdharCard/')),
                ('panCard', models.ImageField(upload_to='Profile/PanCard/')),
                ('Check', models.ImageField(upload_to='Profile/Checks/')),
                ('SalarySlip', models.FileField(blank=True, null=True, upload_to='Profile/SalarySlips/')),
                ('Address', models.CharField(max_length=200)),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='newjoine_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OwnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=250)),
                ('Experience', models.CharField(max_length=600)),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None)),
                ('Projects_Completed', models.IntegerField(default='10+')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
